import type { ProcessedGraph } from '../types';

/**
 * Build G6-compatible graph data from ProcessedGraph.
 *
 * The combos are pre-generated by the Rust backend with:
 * - Unique IDs prefixed with "combo:" to avoid collision with node IDs
 * - Single-child combos already collapsed
 * - Proper parent-child relationships
 */
export function buildGraphData(data: ProcessedGraph) {
  const nodes = data.nodes.map((n) => ({
    id: n.id,
    data: {
      label: n.label,
      node_type: n.node_type,
      violation_count: n.violation_count,
    },
    combo: n.combo,
  }));

  const combos = data.combos.map((c) => ({
    id: c.id,
    label: c.label,
    combo: c.combo,
  }));

  const edges = data.edges.map((e, i) => ({
    id: `${e.source}-${e.target}-${i}`,
    source: e.source,
    target: e.target,
    data: {
      edge_type: e.edge_type,
      weight: e.weight,
    },
  }));

  return { nodes, edges, combos };
}
