import type { ComboData, EdgeData, GraphData, NodeData } from '@antv/g6';
import type { EdgeType, NodeType, ProcessedGraph } from '../types';

/** G6 node data payload */
export interface G6NodeData {
  label: string;
  node_type: NodeType;
  violation_count: number;
  [key: string]: unknown;
}

/** G6-compatible node */
export interface G6Node extends NodeData {
  data: G6NodeData;
}

/** G6 edge data payload */
export interface G6EdgeData {
  edge_type: EdgeType;
  weight: number;
  error_count?: number;
  warn_count?: number;
  info_count?: number;
  [key: string]: unknown;
}

/** G6-compatible edge */
export interface G6Edge extends EdgeData {
  data: G6EdgeData;
}

/** G6-compatible graph data */
export interface G6GraphData extends GraphData {
  nodes: G6Node[];
  edges: G6Edge[];
  combos: ComboData[];
}

/**
 * Build G6-compatible graph data from ProcessedGraph.
 *
 * The combos are pre-generated by the Rust backend with:
 * - Unique IDs prefixed with "combo:" to avoid collision with node IDs
 * - Single-child combos already collapsed
 * - Proper parent-child relationships
 * - Pre-computed layout coordinates (rect)
 */
export function buildGraphData(data: ProcessedGraph): G6GraphData {
  const nodes = data.nodes.map<G6Node>((n) => ({
    id: n.id,
    data: {
      label: n.label,
      node_type: n.node_type,
      violation_count: n.violation_count,
    },
    combo: n.combo,
    style: n.rect
      ? {
          x: n.rect ? n.rect.left + n.rect.width / 2 : undefined,
          y: n.rect ? n.rect.top + n.rect.height / 2 : undefined,
          size: n.rect.height,
        }
      : undefined,
  }));

  const combos = data.combos.map<ComboData>((c) => ({
    id: c.id,
    label: c.label,
    combo: c.combo,
    ...(c.rect
      ? {
          x: c.rect ? c.rect.left : undefined,
          y: c.rect ? c.rect.top : undefined,
          size: [c.rect.width, c.rect.height],
        }
      : undefined),
  }));

  const edges = data.edges.map<G6Edge>((e, i) => ({
    id: `${e.source}-${e.target}-${i}`,
    source: e.source,
    target: e.target,
    data: {
      edge_type: e.edge_type,
      weight: e.weight,
      error_count: e.error_count,
      warn_count: e.warn_count,
      info_count: e.info_count,
    },
  }));

  return { nodes, edges, combos };
}
