import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface ProcessedGraph {
  nodes: {
    id: string;
    label: string;
    node_type: 'file' | 'directory' | 'package';
    path?: string;
    violation_count: number;
    orphan?: boolean;
    children?: string[];
    combo?: string;
  }[];
  edges: {
    source: string;
    target: string;
    edge_type: 'local' | 'npm' | 'core' | 'dynamic';
    weight: number;
    circular?: boolean;
    error_count?: number;
    warn_count?: number;
    info_count?: number;
  }[];
  combos: {
    id: string;
    label: string;
    combo?: string;
  }[];
  meta: {
    original_node_count: number;
    aggregated_node_count: number;
    total_violations: number;
    expanded_dirs?: string[];
  };
  violations: {
    from: string;
    to: string;
    rule: string;
    severity: 'error' | 'warn' | 'info';
    message?: string;
  }[];
}

// WASM module state
let wasmModule: {
  parse_and_aggregate_wasm: (
    inputJson: string,
    maxNodes: number,
    expandedDirs: string[] | null
  ) => ProcessedGraph;
} | null = null;
let wasmInitPromise: Promise<void> | null = null;

async function initWasm(): Promise<void> {
  if (wasmModule) return;
  if (wasmInitPromise) return wasmInitPromise;

  wasmInitPromise = (async () => {
    try {
      // Dynamic import for WASM module
      // @ts-expect-error - WASM module generated by wasm-pack
      const wasm = await import('@dcr-reporter/rust-wasm');
      await wasm.default();
      wasmModule = wasm;
    } catch (e) {
      console.warn('WASM module not available, falling back to native binary:', e);
      wasmInitPromise = null;
      throw e;
    }
  })();

  return wasmInitPromise;
}

function findDcrAggregateBinary(): string | null {
  const isWin = process.platform === 'win32';
  const ext = isWin ? '.exe' : '';

  // Try relative path from CLI dist directory
  try {
    const thisDir = dirname(fileURLToPath(import.meta.url));
    const releaseBin = resolve(thisDir, `../../../rust/target/release/dcr-aggregate${ext}`);
    if (existsSync(releaseBin)) return releaseBin;
    const debugBin = resolve(thisDir, `../../../rust/target/debug/dcr-aggregate${ext}`);
    if (existsSync(debugBin)) return debugBin;
  } catch {}

  return null;
}

/**
 * Convert using native binary (fallback method)
 */
function convertWithBinary(
  dcJson: string,
  maxNodes = 200,
  expandedDirs?: string[]
): ProcessedGraph {
  const binary = findDcrAggregateBinary();

  if (!binary) {
    throw new Error('Rust binary (dcr-aggregate) not found. Please build it with: pnpm build:rust');
  }

  // Write input to temp file for Rust binary
  const tmpDir = mkdtempSync(join(tmpdir(), 'dcr-'));
  const tmpInput = join(tmpDir, 'input.json');
  const tmpOutput = join(tmpDir, 'output.json');
  writeFileSync(tmpInput, dcJson);

  const args = ['--input', tmpInput, '--output', tmpOutput, '--max-nodes', String(maxNodes)];
  if (expandedDirs && expandedDirs.length > 0) {
    args.push('--expanded-dirs', expandedDirs.join(','));
  }

  const result = spawnSync(binary, args, { encoding: 'utf-8' });

  if (result.status !== 0) {
    // Clean up temp files on error
    try {
      unlinkSync(tmpInput);
      unlinkSync(tmpOutput);
      rmdirSync(tmpDir);
    } catch {}
    throw new Error(`Rust binary failed: ${result.stderr || 'Unknown error'}`);
  }

  console.log('convert in rust\n', result.stdout);

  const output = readFileSync(tmpOutput, 'utf-8');
  // Clean up temp files
  try {
    unlinkSync(tmpInput);
    unlinkSync(tmpOutput);
    rmdirSync(tmpDir);
  } catch {}

  return JSON.parse(output) as ProcessedGraph;
}

/**
 * Convert raw dependency-cruiser JSON to ProcessedGraph.
 * Uses WASM if available, falls back to native binary.
 */
export async function convertWithFallback(
  dcJson: string,
  maxNodes = 200,
  expandedDirs?: string[]
): Promise<ProcessedGraph> {
  // Try WASM first
  try {
    await initWasm();
    if (wasmModule) {
      return wasmModule.parse_and_aggregate_wasm(
        dcJson,
        maxNodes,
        expandedDirs || null
      );
    }
  } catch (e) {
    console.warn('WASM failed, falling back to native binary');
  }

  // Fallback to native binary
  return convertWithBinary(dcJson, maxNodes, expandedDirs);
}

/**
 * Synchronous version - only uses native binary, not WASM
 * @deprecated Use async convertWithFallback instead
 */
export function convertWithFallbackSync(
  dcJson: string,
  maxNodes = 200,
  expandedDirs?: string[]
): ProcessedGraph {
  return convertWithBinary(dcJson, maxNodes, expandedDirs);
}